theme: noesya-hugo-theme
paginate: 18
enableRobotsTXT: true
removePathAccents: true
params:
  ecosystem: works
  breadcrumb:
    position: none
  posts:
    date_format: "2006"
    index:
      show_description: false
  seo:
    title:
      separator: "•"