theme: noesya-hugo-theme
paginate: 18
enableRobotsTXT: true
removePathAccents: true
params:
  breadcrumb:
    position: none
  posts:
    index:
      show_description: false
  seo:
    title:
      separator: "•"